# README:
# This setters file is meant for use in codespaces (4vcpu) VMs
# to provide configuration for the EDA platform
# It is conditionally applied in prefs.mk when the codespaces env is detected.
apiVersion: v1
kind: ConfigMap
metadata:
  name: codespaces-4vcpu-apply-setter-fn-config
data:
  # AI Engine
  EAE_REQ_CPU: 10m
  # Artifact server
  ASVR_REQ_CPU: 10m
  # Bootstrap server
  BSVR_REQ_CPU: 100m
  # EDA Cert Checker
  ECC_REQ_CPU: 10m
  # EDA Metrics Server
  EMS_REQ_CPU: 10m
  # Identity Server - Keycloak
  KC_REQ_CPU: 250m
  # Appstore Controller
  ASC_REQ_CPU: 100m
  # Identity Server Database - Postgres
  PG_REQ_CPU: 100m
  # Flow Engine
  FE_REQ_CPU: 100m
  # NPP
  NPP_REQ_CPU: 10m
  # TestMan
  TM_REQ_CPU: 10m