spec:
  npp:
    resources:
      requests:
        cpu: 1m
  testMan:
    resources:
      requests:
        cpu: 1m
  aiEngine:
    resources:
      requests:
        cpu: 1m
  customSettings:
    - applicationName: cx
      settings:
        - name: SrlCpuRequest
          value: 1m
        - name: CxdpCpuRequest
          value: 1m
